# -*- coding: utf-8 -*-
"""instagram_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVPFF2HsScqtkhL0OTaaI1ZxZ7ps8rLL
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import plotly.express as px

# Load data
df = pd.read_csv("Instagram data.csv", encoding='ISO-8859-1')

# Calculate engagement metrics
df['Engagement'] = df['Likes'] + df['Comments'] + df['Shares'] + df['Saves']
df['Engagement Rate (%)'] = round((df['Engagement'] / df['Impressions']) * 100, 2)

# Streamlit UI
st.set_page_config(page_title="Instagram Analytics Dashboard", layout="wide")
st.title("📊 Instagram Analytics Dashboard")

# Metrics
total_impressions = df['Impressions'].sum()
total_likes = df['Likes'].sum()
total_comments = df['Comments'].sum()
total_shares = df['Shares'].sum()
total_saves = df['Saves'].sum()
total_follows = df['Follows'].sum()

col1, col2, col3, col4, col5, col6 = st.columns(6)
col1.metric("Total Impressions", f"{total_impressions:,}")
col2.metric("Total Likes", f"{total_likes:,}")
col3.metric("Total Comments", f"{total_comments:,}")
col4.metric("Total Shares", f"{total_shares:,}")
col5.metric("Total Saves", f"{total_saves:,}")
col6.metric("Total Follows", f"{total_follows:,}")

st.markdown("---")

# Impressions breakdown
impression_sources = ['From Home', 'From Hashtags', 'From Explore', 'From Other']
source_totals = df[impression_sources].sum().reset_index()
source_totals.columns = ['Source', 'Total Impressions']
fig1 = px.pie(source_totals, values='Total Impressions', names='Source', title='Impression Sources Breakdown')
st.plotly_chart(fig1, use_container_width=True)

# Engagement rate distribution
fig2 = px.histogram(df, x='Engagement Rate (%)', nbins=20, title='Engagement Rate Distribution')
st.plotly_chart(fig2, use_container_width=True)

# Top performing posts
top_posts = df.sort_values(by='Engagement Rate (%)', ascending=False).head(5)
fig3 = px.bar(top_posts, x='Engagement Rate (%)', y='Caption', orientation='h', title='Top 5 Posts by Engagement Rate', height=400)
st.plotly_chart(fig3, use_container_width=True)

# Most used hashtags
all_hashtags = df['Hashtags'].dropna().str.lower().str.split()
hashtag_series = pd.Series([tag for sublist in all_hashtags for tag in sublist])
top_hashtags = hashtag_series.value_counts().head(10).reset_index()
top_hashtags.columns = ['Hashtag', 'Count']
fig4 = px.bar(top_hashtags, x='Hashtag', y='Count', title='Top 10 Hashtags Used')
st.plotly_chart(fig4, use_container_width=True)

st.markdown("---")
st.caption("Instagram Data Dashboard | Powered by Streamlit")

!streamlit run instagram_dashboard.py

!streamlit run /usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py